
%% Required input:

% Description: This script utilises data deposited at 
% https://drive.google.com/open?id=1zFp5v1qG-q9cFrMn27-ScQVBakTFC2HO
% This script is used to reproduce Figure 8 and 9 within the research
%  paper of Pearce et al. (2020) An Evaluation of Image Velocimetry Techniques under Low Flow Conditions 
%and High Seeding Densities Using Unmanned Aerial Systems. Journal Remote Sensing 
%(SI: Unamnned Aerial Systems for Surface Hydrology).

% Inputs: 
% This script requires the data produced from all of the
% xs_adcp_analysis_(algorithm) scripts. 
% Example inputs can also be found at: https://drive.google.com/open?id=1zFp5v1qG-q9cFrMn27-ScQVBakTFC2HO
% In the folder: ADCP_Comparisons\All_XS_14112019.mat
% If using the example dataset, please either change the Variable names
% from 'KLT_VidA' to 'KLT' or change the variables within the script to 'KLT_VidA' wherever
% 'KLT' is entered, for example. 



t = 1;
fig = gcf;
ADCPcolor = [0,0,0];
KLTcolor = [166/255,206/255,227/255]; % adapted from http://colorbrewer2.org
PIVcolor = [31/255,120/255,180/255];
PTVcolor = [178/255,223/255,138/255];
OTVcolor = [51/255,160/255,44/255];
 SSIVcolor = [251/255,154/255,153/255]; 


xlims = [floor(nanmin(ADCP(:,1))),ceil(nanmax(ADCP(:,1)))];


%% Transect Three (Upstream)

ax1 = subplot(3,2,1);
hold on;
pbaspect([4 2 2])

plot(ADCP(:,t),ADCP(:,t+1),...
    'color',ADCPcolor,...
    'linestyle','-',...
    'linewidth',2);

plot(KLT(:,t),KLT(:,t+1),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t),PIV(:,t+1),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t),PTV(:,t+1),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


 
 plot(SSIV(:,t),SSIV(:,t+1),...
     'color',SSIVcolor,...
     'linestyle','-',...
     'linewidth',1.5);
 
 plot(OTV(:,t),OTV(:,t+1),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);
 

set(gca,'TickLabelInterpreter','latex')
set(ax1,'xLim',xlims);

ax3 = subplot(3,2,2);
hold on;
pbaspect([2 1 1])

plot(KLT(:,t),(KLT(:,t+1)-ADCP(:,t+1)),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t),(PIV(:,t+1)-ADCP(:,t+1)),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t),(PTV(:,t+1)-ADCP(:,t+1)),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);



plot(SSIV(:,t),(SSIV(:,t+1)-ADCP(:,t+1)),...
    'color',SSIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(OTV(:,t),(OTV(:,t+1)-ADCP(:,t+1)),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot([xlims(1),xlims(2)],[0,0],... % Add dashed line at zero
    'color',[0.5 0.5 0.5],...
    'linestyle','--',...
    'linewidth',1);

set(ax3,'xLim',xlims)
input1 = get(ax3(1),'YTickLabel');
input2 = get(ax3(1),'YTick');
input3 = get(ax3(1),'YLim');
input4 = get(ax3(1),'YLim');

ax1_pos = ax3.Position; % position of first axes
set(ax1(1),'YColor',[0,0,0])
ax4 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');

set(ax4,'xLim',xlims);
set(ax4,'YTick',str2double(input1));
set(ax4,'YTickLabel',str2double(input1));
set(ax4,'Ylim',input3);
set(ax3,'YColor',[1,1,1]);
set(ax4,'XColor',[1,1,1]);
set(ax4,'XTick','');
set(ax3,'YTick','');
set(ax3,'TickLabelInterpreter','latex')
set(ax4,'TickLabelInterpreter','latex')



%xlabel('y co-ordinates (m)', 'Interpreter','LaTex')
%ylabel('Velocity Magnitude $\mathrm{(m \ s^{-1})}$' , 'Interpreter','LaTex')


%% Transect Four (middle)

ax5 = subplot(3,2,3);
hold on;
pbaspect([2 1 1])

set(gca,'TickLabelInterpreter','latex')

plot(ADCP(:,t+2),ADCP(:,t+3),...
    'color',ADCPcolor,...
    'linestyle','-',...
    'linewidth',2);

plot(KLT(:,t+2),KLT(:,t+3),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t+2),PIV(:,t+3),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t+2),PTV(:,t+3),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);




plot(SSIV(:,t+2),SSIV(:,t+3),...
    'color',SSIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(OTV(:,t+2),OTV(:,t+3),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);



set(ax5,'xLim',xlims);
ylabel('Downstream Velocity $\mathrm{[m \ s^{-1}]}$' , 'Interpreter','LaTex')


ax6 = subplot(3,2,4);
hold on;
pbaspect([2 1 1])

set(gca,'TickLabelInterpreter','latex')
plot(KLT(:,t+2),(KLT(:,t+3)-ADCP(:,t+3)),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t+2),(PIV(:,t+3)-ADCP(:,t+3)),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t+2),(PTV(:,t+3)-ADCP(:,t+3)),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot(SSIV(:,t+2),(SSIV(:,t+3)-ADCP(:,t+3)),...
    'color',SSIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot(OTV(:,t+2),(OTV(:,t+3)-ADCP(:,t+3)),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


 plot([xlims(1),xlims(2)],[0,0],... % Add dashed line at zero
     'color',[0.5 0.5 0.5],...
     'linestyle','--',...
     'linewidth',1);

 set(ax6,'xLim',xlims)
input1 = get(ax6(1),'YTickLabel');
input2 = get(ax6(1),'YTick');
input3 = get(ax6(1),'YLim');
input4 = get(ax6(1),'YLim');

ax1_pos = ax6.Position; % position of first axes
set(ax6(1),'YColor',[0,0,0])
ax7 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');

set(ax7,'xLim',xlims);
set(ax7,'YTick',str2double(input1));
set(ax7,'YTickLabel',str2double(input1));
set(ax7,'Ylim',input3);
set(ax6,'YColor',[1,1,1]);
set(ax7,'XColor',[1,1,1]);
set(ax7,'XTick','');
set(ax6,'YTick','');
set(ax6,'TickLabelInterpreter','latex')
set(ax7,'TickLabelInterpreter','latex')

ylabel('Difference from ADCP $\mathrm{[m \ s^{-1}]}$' , 'Interpreter','LaTex')


%% Transect Five (Downstream)

ax8 = subplot(3,2,5);
hold on;
pbaspect([2 1 1])

set(gca,'TickLabelInterpreter','latex')

plot(ADCP(:,t+4),ADCP(:,t+5),...
    'color',ADCPcolor,...
    'linestyle','-',...
    'linewidth',2);

plot(KLT(:,t+4),KLT(:,t+5),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t+4),PIV(:,t+5),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t+4),PTV(:,t+5),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot(SSIV(:,t+4),SSIV(:,t+5),...
    'color',SSIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot(OTV(:,t+4),OTV(:,t+5),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


set(ax8,'xLim',xlims);
xlabel('Distance across the channel (m)', 'Interpreter','LaTex')


ax9 = subplot(3,2,6);
hold on;
pbaspect([2 1 1])

set(gca,'TickLabelInterpreter','latex')
plot(KLT(:,t+4),(KLT(:,t+5)-ADCP(:,t+5)),...
    'color',KLTcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PIV(:,t+4),(PIV(:,t+5)-ADCP(:,t+5)),...
    'color',PIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(PTV(:,t+4),(PTV(:,t+5)-ADCP(:,t+5)),...
    'color',PTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot(SSIV(:,t+4),(SSIV(:,t+5)-ADCP(:,t+5)),...
    'color',SSIVcolor,...
    'linestyle','-',...
    'linewidth',1.5);

plot(OTV(:,t+4),(OTV(:,t+5)-ADCP(:,t+5)),...
    'color',OTVcolor,...
    'linestyle','-',...
    'linewidth',1.5);


plot([xlims(1),xlims(2)],[0,0],... % Add dashed line at zero
    'color',[0.5 0.5 0.5],...
    'linestyle','--',...
    'linewidth',1);
% 
% xlabel('y co-ordinates (m)', 'Interpreter','LaTex')

set(ax9,'xLim',xlims)
input1 = get(ax9(1),'YTickLabel');
input2 = get(ax9(1),'YTick');
input3 = get(ax9(1),'YLim');
input4 = get(ax9(1),'YLim');

ax1_pos = ax9.Position; % position of first axes
set(ax9(1),'YColor',[0,0,0])
ax10 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');

set(ax10,'xLim',xlims);
set(ax10,'YTick',str2double(input1));
set(ax10,'YTickLabel',str2double(input1));
set(ax10,'Ylim',input3);
set(ax9,'YColor',[1,1,1]);
set(ax10,'XColor',[1,1,1]);
set(ax10,'XTick','');
set(ax9,'YTick','');
set(ax9,'TickLabelInterpreter','latex')
set(ax10,'TickLabelInterpreter','latex')

